# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(658, 493)
        Login.setStyleSheet("background-color: rgb(164, 254, 255);")
        self.verticalLayoutWidget = QtWidgets.QWidget(Login)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(157, 91, 331, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Create_user = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.Create_user.setFont(font)
        self.Create_user.setStyleSheet("background-color: rgb(106, 255, 7);")
        self.Create_user.setObjectName("Create_user")
        self.verticalLayout.addWidget(self.Create_user)
        self.Sign_in = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.Sign_in.setFont(font)
        self.Sign_in.setStyleSheet("background-color: rgb(71, 83, 255);")
        self.Sign_in.setObjectName("Sign_in")
        self.verticalLayout.addWidget(self.Sign_in)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.Create_user.setText(_translate("Login", "Создать пользователя"))
        self.Sign_in.setText(_translate("Login", "Авторизоваться"))
